config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :topics do
    resources :concepts

    post :subscribe
  end

  resources :concepts, only: [] do
    post :learn
  end

  resources :embeds

  root to: 'topics#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :topic

  has_many :concept_learnings, dependent: :destroy
  has_many :users, through: :concept_learnings

  has_rich_text :content

  has_one_attached :featured_image, dependent: :destroy

  validates :featured_image, presence: true
  validates :learning_time_minutes, presence: true
  validates :short_description, presence: true
  validates :title, presence: true
end

app/models/concept_learning.rb
class ConceptLearning < ApplicationRecord

  belongs_to :concept
  belongs_to :user

end

app/models/embed.rb
class Embed < ApplicationRecord
  include ActionText::Attachable

  validates :content, presence: true

  after_validation :fetch_oembed_data

  def to_partial_path
    "embeds/embed"
  end

  def fetch_oembed_data
    url =
      case content
      when /youtube/
        "https://www.youtube.com/oembed?url=#{content}&format=json"
      when /soundcloud/
        "https://soundcloud.com/oembed?url=#{content}&format=json"
      when /twitter/
        "https://publish.twitter.com/oembed?url=#{content}"
      end
    res = RestClient.get url
    json = JSON.parse(res.body, object_class: OpenStruct)
    self.height = json.height
    self.author_url = json.author_url
    self.thumbnail_url = json.thumbnail_url
    self.width = json.width
    self.author_name = json.author_name
    self.thumbnail_height = json.thumbnail_height
    self.title = json.title
    self.version = json.version
    self.provider_url = json.provider_url
    self.thumbnail_width = json.thumbnail_width
    self.embed_type = json.type
    self.provider_name = json.provider_name
    self.html = json.html
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :concepts, dependent: :destroy

  has_many :topic_subscriptions, dependent: :destroy
  has_many :users, through: :topic_subscriptions

  belongs_to :creator, class_name: 'User', foreign_key: :created_by

  has_one_attached :featured_image, dependent: :destroy

  validates :featured_image, presence: true
  validates :short_description, presence: true
  validates :name, presence: true
end

app/models/topic_subscription.rb
class TopicSubscription < ApplicationRecord

  belongs_to :topic
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :topic_subscriptions
  has_many :topics, through: :topic_subscriptions

  has_many :concept_learnings
  has_many :concepts, through: :concept_learnings

  has_one_attached :avatar, dependent: :destroy

  validates :full_name, presence: true
  validates :avatar, presence: true

  def topic_creator?(topic)
    topic.created_by == id
  end

  def subscribed?(topic)
    topic_subscriptions.where(topic: topic).present?
  end

  def learned?(concept)
    concept_learnings.where(concept: concept).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:full_name, :email, :avatar, :password, :password_confirmation)
    end
  end
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController

  before_action :authenticate_user!, only: %i[new create learn]

  def new
    @topic = Topic.find(params[:topic_id])
    @concept = @topic.concepts.build
  end

  def create
    @topic = Topic.find(params[:topic_id])

    @concept = @topic.concepts.build(concept_params)
    @concept.created_by = current_user.id
    @concept.save
    redirect_to topic_concepts_path(@topic)
  end

  def index
    @topic = Topic.find(params[:topic_id])
    @concepts = @topic.concepts.with_rich_text_content_and_embeds
  end

  def show
    @concept = Concept.find(params[:id])
    @topic = @concept.topic
  end

  def learn
    concept = Concept.find(params[:concept_id])
    current_user.concept_learnings.find_or_create_by(concept: concept)
    redirect_to topic_concept_path(concept.topic, concept)
  end

  private

  def concept_params
    params.require(:concept).permit(:title, :content, :featured_image, :short_description, :learning_time_minutes)
  end

end

app/controllers/embeds_controller.rb
class EmbedsController < ApplicationController

  def create
    @embed = Embed.create!(params.require(:embed).permit(:content))

    respond_to do |format|
      format.json
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, only: %i[new create subscribe]

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.created_by = current_user.id
    @topic.save
    redirect_to topics_path
  end

  def index
    @topics = Topic.all
  end

  def subscribe
    topic = Topic.find(params[:topic_id])
    current_user.topic_subscriptions.find_or_create_by(topic: topic)
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :featured_image, :short_description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :full_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/concepts/index.html.slim
section class="space--sm"
  .container
    .row
      - @concepts.each do |concept|
        .col-md-3
          .card.card-2.text-center
            .card__top
              - if user_signed_in? && current_user.learned?(concept)
                span class="label" Learned
              = link_to topic_concept_path(@topic, concept) do
                - if concept.featured_image.attached?
                  = image_tag concept.featured_image
            .card__body
              = link_to topic_concept_path(@topic, concept) do
                h4
                  = concept.title
              span class="type--fade" #{concept.learning_time_minutes} minutes
              p
                = concept.short_description
            .card__bottom

  .container
    .row
      - if current_user
        = link_to 'New concept', new_topic_concept_path(@topic)

app/views/concepts/new.html.slim
.container
  .row
    .col-8
      = simple_form_for [@topic, @concept] do |f|
        .row
          .col-12
            = f.input :title

          .col-12
            = f.input :featured_image

          .col-12
            = f.input :short_description

          .col-12
            = f.input :learning_time_minutes

          .col-12
            = f.input :content, as: :rich_text_area, input_html: { data: { embeds_path: embeds_path(@concept, format: :json) } }

          .col-12
            = f.submit

app/views/concepts/show.html.slim
section class="space--sm"
  .container
    .row
      .col-md-12
        h2
          = @concept.title

        p
          =h @concept.content

- if user_signed_in? && current_user.learned?(@concept)
  p learned
- else
  = link_to 'Learn', concept_learn_path(@concept), method: :post

app/views/embeds/_embed.html.slim
.youtube-embed.embed
  .content
    = image_tag(embed.thumbnail_url) if embed.thumbnail_url.present?
    p = "Embed from #{embed.provider_name} (#{embed.content})"
    p.embed-html = embed.html

app/views/layouts/_header.html.slim
.bar.bar--sm.visible-xs
  .container
    .row
      .col-3.col-md-2
        = link_to topics_path do
          = image_tag "polygon.png", class: "logo logo-dark"

      .col-9.col-md-10.text-right
        a href="#" class="hamburger-toggle" data-toggle-class="#menu5;hidden-xs hidden-sm"
          i class="icon icon--sm stack-interface stack-menu"

nav class="bar bar--sm"
  .container
    .row
      .col-lg-1.hidden-xs.hidden-sm
        .bar__module
          = link_to topics_path do
            = image_tag "polygon.png", class: "logo logo-dark"

      .col-lg-5.hidden-xs.hidden-sm
        .bar__module
          ul class="menu-horizontal"
            li
              = link_to topics_path do
                i class="stack-interface"
                | Topics
            - if @topic&.persisted?
              li
                = link_to topic_concepts_path(@topic) do
                  i class="stack-interface"
                  = @topic.name

      .col-lg-6.text-right.text-left-xs
        - if user_signed_in?
          .bar__module
            ul class="menu-horizontal"
              li
                = image_tag(current_user.avatar, width: 20, class: 'avatar image--xxs') if current_user.avatar.attached?
                = current_user.full_name

        - else
          .bar__module
            = link_to new_user_session_path, class: "btn btn--sm type--uppercase" do
              span class="btn__text"
                | Log In
            = link_to new_user_registration_path, class: "btn btn--primary btn--sm type--uppercase" do
              span class="btn__text"
                | Register

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>LearnMore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,400i,500,600,700%7CMerriweather:300,300i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>

</html>

app/views/topics/index.html.slim
section class="space--sm"
  .container
    .row
      - @topics.each do |topic|
        .col-md-6.mb-3
          .card.card-2.text-center
            .card__top
              = link_to topic_concepts_path(topic) do
                - if topic.featured_image.attached?
                  = image_tag topic.featured_image
            .card__body
              = link_to topic_concepts_path(topic) do
                h4
                  = topic.name

              span class="type--fade" by #{topic.creator.full_name}
              p
                = topic.short_description

            .card__bottom.text-center
              .card__action
                - if user_signed_in? && current_user.subscribed?(topic)
                  span class="h6 type--uppercase type--fade" Subscribed
                  a href="#" disabled=true
                    i class="material-icons" flip_to_front
                - else
                  span class="h6 type--uppercase" Subscribe
                  = link_to topic_subscribe_path(topic), method: :post do
                    i class="material-icons" flip_to_front
  .container
    .row
      - if current_user
        = link_to 'New topic', new_topic_path

app/views/topics/new.html.slim
.container
  .row
    .col-8
      = simple_form_for @topic do |f|
        .row
          .col-12
            = f.input :name

          .col-12
            = f.input :short_description

          .col-12
            = f.input :featured_image

          .col-12
            = f.submit

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <span class="type--fine-print block">Already have an account?
    <%= link_to "Log in", new_session_path(resource_name) %>
  </span>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <span class="type--fine-print block">Dont have an account yet?
    <%= link_to "Create account", new_registration_path(resource_name) %>
  </span>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <span class="type--fine-print block">Forgot your username or password?
    <%= link_to "Recover Account", new_password_path(resource_name) %>
  </span>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <br />
  <span class="type--fine-print block">Didn't receive confirmation instructions?
    <%= link_to "Send again", new_confirmation_path(resource_name) %>
  </span>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>